"""initial migration

Revision ID: 469a3de85ad9
Revises: 
Create Date: 2026-05-03 19:27:46.809950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '469a3de85ad9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasktype',
    sa.Column('taskid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('taskid'),
    sa.UniqueConstraint('taskid')
    )
    op.create_table('users',
    sa.Column('userid', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('userid'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('userid'),
    sa.UniqueConstraint('username')
    )
    op.create_table('tasks',
    sa.Column('tasksid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('descr', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('typeId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['typeId'], ['tasktype.taskid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['users.userid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tasksid'),
    sa.UniqueConstraint('tasksid')
    )
    op.create_table('steps',
    sa.Column('stepid', sa.UUID(), nullable=False),
    sa.Column('steptitle', sa.String(), nullable=False),
    sa.Column('orderidx', sa.Integer(), nullable=False),
    sa.Column('orderstatus', sa.String(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('allocatedHours', sa.DECIMAL(precision=10, scale=3), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completedAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('taskID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['taskID'], ['tasks.tasksid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('stepid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('steps')
    op.drop_table('tasks')
    op.drop_table('users')
    op.drop_table('tasktype')
    # ### end Alembic commands ###
