"""add step constraints and completed_at

Revision ID: 4975d5f687e2
Revises: 13967a17ebec
Create Date: 2026-05-01 15:19:37.926715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4975d5f687e2'
down_revision: Union[str, Sequence[str], None] = '13967a17ebec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('step', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'step', ['execution_unit_id', 'order_index'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'step', type_='unique')
    op.drop_column('step', 'completed_at')
    # ### end Alembic commands ###
